= gradle-metal
:author: Pedro Lamarão <pedro.lamarao@gmail.com>

Gradle Metal is a suite of Gradle plugins supporting development for the bare metal,
primarily design to support project link:https://github.com/pedrolamarao/metal[Metal].

Features:

* compile assembler, c and c++ (including c++ module interfaces)
* assemble archives and executables
* build target support (e.g. `x86_64-elf`)
* generate compilation commands database
* source dependency on included project
* binary dependency on prebuilt external project
* LLVM tools

[WARNING]
This project is under early development.
Compatibility *will be broken* without prior notice.
In particular, we will *not* stabilize our Gradle dependency before Gradle 9.

Current requirements:

* Gradle 8.4 or newer
* JDK 17 or newer
* LLVM 16 or newer (with clang, clang-scan-deps, lld, llvm-ar etc.)

To use the development version, you may install from source with `./gradlew publishToMavenLocal` and configure your project's settings like this:

[source]
----
pluginManagement {
    repositories {
        mavenLocal()
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id.startsWith("br.dev.pedrolamarao.metal.")) {
                useModule("br.dev.pedrolamarao.gradle.metal:plugins:0.5+")
            }
        }
    }
}
----

Check the link:samples[] for a variety of use-cases.

Plugins:

* `br.dev.pedrolamarao.metal.base`: adds the Gradle Metal service and extension
* `br.dev.pedrolamarao.metal.application`: conventional application project
* `br.dev.pedrolamarao.metal.archive`: conventional archive project
* `br.dev.pedrolamarao.metal.asm`:  adds assembler source sets
* `br.dev.pedrolamarao.metal.c`: adds C sources sets
* `br.dev.pedrolamarao.metal.cpp`: adds C preprocessor source sets
* `br.dev.pedrolamarao.metal.cxx`: adds C++ module implementation source sets
* `br.dev.pedrolamarao.metal.ixx`: adds C++ module interface source sets

Under construction:

* build flavour support (e.g. `debug`, `release`)
* shared library component
* source dependencies on cmake project
* binary dependencies on maven repository
* GCC tools
* MSVC tools

For development status, see Github issues at link:https://github.com/pedrolamarao/gradle-metal/issues[].