= base metal application with multiboot2

This sample demonstrates a multiboot2 application.

Multiboot2 is a "boot protocol" that allows boot loaders to load applications.
The boot loader shall load the application into memory and call into the application's entry point.
The `protocol` library defines "start" code to call a familiar "main" function.

This sample generates an ELF application image from user C++ sources with the usual tools.
It then generates a multiboot2 application image from that with GRUB 2 tools, which are required to be in the environment.
The target machine is hard-coded in `gradle.properties` and currently must stay that way.

To build this sample inside a `gradle-metal` source tree, run:

[source,shell]
----
../../gradlew --include-build=../.. build`
----

If the build fails with something similar to the below, set `grub.path` in `gradle.properties`.
GRUB is failing to detect its own install path.

----
grub-mkstandalone: error: /foo/gradle-cxx/samples/multiboot2/i386-pc/modinfo.sh doesn't exist. Please specify --target or --directory.
----

To run this sample with QEMU:

[source,shell]
----
qemu-system-i386 -machine q35 -debugcon vc -kernel build/image
----

It is expected that the application will print "gradle-metal" to debugcon.