name: "publish"
on: [workflow_dispatch]
jobs:
  publish:
    name: "publish"
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Validate Gradle Wrapper"
        uses: gradle/wrapper-validation-action@v1
      - name: "Set up JDK 17"
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - name: "Publish with Gradle"
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishPlugins "-Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }}" "-Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}" --validate-only