name: "windows"
on: [pull_request,workflow_dispatch]
jobs:
  build:
    name: "build"
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Validate Gradle Wrapper"
        uses: gradle/wrapper-validation-action@v1
      - name: "Set up JDK 17"
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"
      - name: "Build with Gradle"
        uses: gradle/gradle-build-action@v2.8.0
        with:
          arguments: build
      - name: "Test Report"
        uses: phoenix-actions/test-reporting@v8
        id: test-report               # Set ID reference for step
        if: success() || failure()    # run this step even if previous step failed
        with:
            name: JUnit Tests            # Name of the check run which will be created
            path: "**/build/test-results/**/*.xml"    # Path to test results
            reporter: java-junit        # Format of test results
