name: "windows"
on: [pull_request,workflow_dispatch]
jobs:
  build:
    name: "build"
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Validate Gradle Wrapper"
        uses: gradle/wrapper-validation-action@v2
      - name: "Set up JDK 17"
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"
      - name: "Build with Gradle"
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build
      - name: "Generate Allure Report"
        uses: gradle/gradle-build-action@v3
        with:
            arguments: allureAggregateReport
      - name: "Publish Allure Report"
        uses: actions/upload-artifact@v4
        if: always()
        with:
            name: windows-latest-jdk-17
            path: "build/reports/allure-report/allureAggregateReport/index.html"